version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
